[build]
  publish = "dist"

[[redirects]]
  from = "/about-us"
  to = "/about-us.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/testimonials"
  to = "/testimonials.html"
  status = 200

[[redirects]]
  from = "/*"              # Catch-all for any other route
  to = "/index.html"
  status = 200